# Generated by Django 3.2.8 on 2023-09-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('company_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('company_domain', models.CharField(blank=True, max_length=1000, null=True)),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('inductry', models.CharField(blank=True, max_length=1000, null=True)),
                ('size_range', models.CharField(blank=True, max_length=1000, null=True)),
                ('locality', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('current_employee_estimate', models.IntegerField(blank=True, null=True)),
                ('total_employee_estimate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
