# Generated by Django 3.2.8 on 2023-09-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalystCountApp', '0002_rename_inductry_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='current_employee_estimate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_employee_estimate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_founded',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
