# Generated by Django 3.2.8 on 2023-09-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatalystCountApp', '0003_auto_20230910_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
